version: '3.4'
services:
  iqfeed:
    image: jaikumarm/iqfeed:v6011
    ports:
     - "5009:5010"
     - "5901:5901"     
     - "9100:9101"
     - "9300:9301"
    environment:
      IQFEED_PRODUCT_ID: "${DTN_PRODUCT_ID}"
      IQFEED_LOGIN: "${DTN_ID}"
      IQFEED_PASSWORD: "${DTN_PW}"
    volumes:
      - /var/log/iqfeed:/home/wine/DTN/IQFeed      
    healthcheck:
      test: ["CMD", "python3", "/home/wine/is_iqfeed_running.py"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 1m

  autoheal:
    image: willfarrell/autoheal:latest
    restart: always
    environment:
      AUTOHEAL_CONTAINER_LABEL: iqfeed
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: autoheal      
